import{initializeApp,getApps}from'https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js';
import{getAuth}from'https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js';
import{getFirestore,collection,doc,getDoc,getDocs,addDoc,setDoc,serverTimestamp}from'https://www.gstatic.com/firebasejs/10.7.0/firebase-firestore.js';
import{GOOGLE_CLIENT_ID,DRIVE_SCOPE}from'./drive-config.js';

const firebaseConfig={apiKey:'AIzaSyBTDfFNbtXgf6I02wS_f6nCXLym2eSzc8',authDomain:'note-competition.firebaseapp.com',projectId:'note-competition',storageBucket:'note-competition.firebasestorage.app',messagingSenderId:'742140044633',appId:'1:742140044633:web:36cb08ff2aafc23c111848'};
// The existing messenger module already initializes Firebase; reuse it when possible.
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const uid=localStorage.getItem('uid'),nickname=localStorage.getItem('nickname');
let tokenClient=null,accessToken=null,tokenResolve=null,tokenReject=null;
const $=id=>document.getElementById(id);

function esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function chatId(a,b){return[a,b].sort().join('_')}
function fmtSize(n){if(!n)return'';const u=['B','KB','MB','GB'];let i=0,x=n;while(x>=1024&&i<u.length-1){x/=1024;i++}return`${x.toFixed(i?1:0)} ${u[i]}`}
function isConfigured(){return GOOGLE_CLIENT_ID&&!GOOGLE_CLIENT_ID.startsWith('PASTE_')}
function loadGIS(){return new Promise((resolve,reject)=>{if(window.google?.accounts?.oauth2)return resolve();const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.onload=()=>resolve();s.onerror=()=>reject(new Error('Google Identity Services could not load.'));document.head.appendChild(s)})}
async function getToken(interactive=true){if(!isConfigured())throw new Error('GOOGLE_CLIENT_ID_NOT_CONFIGURED');if(accessToken)return accessToken;await loadGIS();return new Promise((resolve,reject)=>{tokenResolve=resolve;tokenReject=reject;if(!tokenClient)tokenClient=google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CLIENT_ID,scope:DRIVE_SCOPE,callback:r=>{if(r.error){accessToken=null;tokenReject?.(new Error(r.error));return}accessToken=r.access_token;tokenResolve?.(accessToken);tokenResolve=tokenReject=null;}});tokenClient.requestAccessToken({prompt:interactive?'consent':''})})}
async function driveFetch(url,options={},retry=true){let t=await getToken(true);let r=await fetch(url,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${t}`}});if(r.status===401&&retry){accessToken=null;t=await getToken(true);r=await fetch(url,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${t}`}})}if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r}
async function getGoogleIdentity(){const r=await driveFetch('https://www.googleapis.com/drive/v3/about?fields=user(displayName,emailAddress,permissionId)');return r.json()}
async function linkGoogle(){if(!uid)return;const me=await getGoogleIdentity();await setDoc(doc(db,'users',uid),{googleDriveLinked:true,googleEmail:me.user?.emailAddress||'',googleDisplayName:me.user?.displayName||'',googleDriveLinkedAt:serverTimestamp()},{merge:true});return me.user}
async function sharePublic(fileId){await driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}/permissions?fields=id,type,role`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'anyone',role:'reader',allowFileDiscovery:false})});}
async function uploadResumable(file,onProgress){const init=await driveFetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable',{method:'POST',headers:{'Content-Type':'application/json; charset=UTF-8','X-Upload-Content-Type':file.type||'application/octet-stream','X-Upload-Content-Length':String(file.size)},body:JSON.stringify({name:file.name,mimeType:file.type||'application/octet-stream'})});const session=init.headers.get('Location');if(!session)throw new Error('Drive did not return an upload session.');let start=0;const chunkSize=8*1024*1024;while(start<file.size){const end=Math.min(start+chunkSize,file.size);const r=await fetch(session,{method:'PUT',headers:{'Content-Length':String(end-start),'Content-Range':`bytes ${start}-${end-1}/${file.size}`},body:file.slice(start,end)});if(r.status===308){const range=r.headers.get('Range');start=range?Number(range.match(/-(\d+)$/)?.[1]||end-1)+1:end;onProgress?.(start/file.size)}else if(r.ok){onProgress?.(1);return r.json()}else{throw new Error(`Upload failed: ${r.status} ${r.statusText}`)}}}
async function uploadFile(file){if(!file||!uid)throw new Error('No file selected.');const result=await uploadResumable(file,p=>setStatus(`Uploading ${Math.round(p*100)}%…`));await sharePublic(result.id);return{fileId:result.id,fileName:file.name,mimeType:file.type||'application/octet-stream',size:file.size,shareUrl:`https://drive.google.com/file/d/${result.id}/view?usp=sharing`,previewUrl:file.type?.startsWith('image/')?`https://drive.google.com/uc?export=view&id=${result.id}`:null,downloadUrl:`https://drive.google.com/uc?export=download&id=${result.id}`}}
async function currentChat(){const title=$('title')?.textContent?.trim()||'Everyone';if(title==='Everyone')return{id:'global',name:'Everyone'};const s=await getDocs(collection(db,'users'));const u=s.docs.map(d=>d.data()).find(x=>x.uid!==uid&&x.nickname===title&&!x.kicked);if(!u)throw new Error('Open a chat with the recipient first.');return{id:chatId(uid,u.uid),name:u.nickname,other:u.uid}}
async function sendMediaMessage(media){const c=await currentChat();const text=`[[MEDIA]]${JSON.stringify(media)}`;await setDoc(doc(db,'chats',c.id),c.id==='global'?{type:'group',name:'Everyone',lastMessage:`${media.kind==='image'?'🖼️':'📎'} ${media.fileName}`,lastSender:uid,updatedAt:serverTimestamp()}:{type:'personal',members:[uid,c.other],lastMessage:`${media.kind==='image'?'🖼️':'📎'} ${media.fileName}`,lastSender:uid,updatedAt:serverTimestamp()},{merge:true});await addDoc(collection(db,'chats',c.id,'messages'),{text,sender:uid,senderName:nickname,createdAt:serverTimestamp(),edited:false,media:true})}
function setStatus(t){const e=$('driveStatus');if(e)e.textContent=t}
function showMediaCard(media){return`<div class="driveMediaCard"><div class="driveMediaIcon">${media.kind==='image'?'🖼️':media.mimeType==='application/pdf'?'📄':'📎'}</div><div class="driveMediaInfo"><b>${esc(media.fileName)}</b><small>${fmtSize(media.size)}</small></div><a href="${esc(media.downloadUrl)}" target="_blank" rel="noopener noreferrer" class="driveDownload">Download</a></div>`}
function upgradeMediaRendering(){const root=$('messages');if(!root)return;const process=()=>root.querySelectorAll('.bubble').forEach(b=>{const raw=b.textContent||'';if(!raw.startsWith('[[MEDIA]]')||b.dataset.mediaDone)return;try{const m=JSON.parse(raw.slice(9));b.dataset.mediaDone='1';if(m.kind==='image'){b.innerHTML=`<a href="${esc(m.shareUrl)}" target="_blank" rel="noopener noreferrer" class="driveImageLink"><img class="driveImage" loading="lazy" src="${esc(m.previewUrl||m.downloadUrl)}" alt="${esc(m.fileName)}"></a><div class="driveCaption">${esc(m.fileName)} · ${fmtSize(m.size)}</div>`}else{b.innerHTML=showMediaCard(m)}}catch{}});new MutationObserver(process).observe(root,{childList:true,subtree:true});process()}
function panel(){const v=$('mediaView');if(!v)return;v.innerHTML=`<div class="drivePanel"><div class="driveTitle">☁️ Google Drive Media</div><div class="driveDesc">Upload images, PDFs, voice, videos and files to your Google Drive. Tanmira Chat only stores the Drive link in the message.</div><button id="connectDrive" class="drivePrimary">🔗 Connect Google Drive</button><input id="driveFilePicker" type="file" hidden multiple><button id="drivePick" class="driveSecondary" disabled>📎 Choose files</button><div id="driveStatus" class="driveStatus"></div></div>`;const connect=$('connectDrive'),pick=$('drivePick'),picker=$('driveFilePicker');connect.onclick=async()=>{try{connect.disabled=true;setStatus('Connecting to Google…');const me=await linkGoogle();connect.textContent=`✅ Connected: ${me.emailAddress||'Google Drive'}`;pick.disabled=false;setStatus('Google Drive connected.');}catch(e){console.error(e);alert(e.message==='GOOGLE_CLIENT_ID_NOT_CONFIGURED'?'First add your Google OAuth Web Client ID in js/drive-config.js.':'Google Drive connection failed. '+e.message)}finally{connect.disabled=false}};pick.onclick=()=>picker.click();picker.onchange=async()=>{for(const file of picker.files){try{setStatus(`Preparing ${file.name}…`);const media=await uploadFile(file);await sendMediaMessage({...media,kind:file.type.startsWith('image/')?'image':'file'});setStatus(`✅ Sent ${file.name}`)}catch(e){console.error(e);alert(`Could not send ${file.name}: ${e.message}`)}}picker.value=''}}
function injectStyles(){if(document.getElementById('driveStyles'))return;const s=document.createElement('style');s.id='driveStyles';s.textContent=`.drivePanel{padding:18px;max-width:620px;margin:18px auto;border:1px solid rgba(255,255,255,.08);border-radius:18px;background:rgba(255,255,255,.03)}.driveTitle{font-size:20px;font-weight:700;margin-bottom:8px}.driveDesc{color:#9aa6bd;font-size:13px;line-height:1.5;margin-bottom:16px}.drivePrimary,.driveSecondary{border:0;border-radius:12px;padding:11px 15px;cursor:pointer;margin-right:8px;font-weight:700}.drivePrimary{background:var(--accent,#5865f2);color:#fff}.driveSecondary{background:rgba(255,255,255,.08);color:var(--text,#fff)}.driveSecondary:disabled{opacity:.45;cursor:not-allowed}.driveStatus{margin-top:14px;color:#9aa6bd;font-size:12px}.driveImageLink{display:block}.driveImage{display:block;max-width:min(320px,100%);max-height:420px;border-radius:14px;object-fit:contain}.driveCaption{font-size:11px;color:#9aa6bd;margin-top:5px}.driveMediaCard{display:flex;align-items:center;gap:10px;min-width:220px}.driveMediaIcon{font-size:30px}.driveMediaInfo{display:flex;flex-direction:column;flex:1;min-width:0}.driveMediaInfo b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.driveMediaInfo small{color:#9aa6bd;margin-top:3px}.driveDownload{font-size:12px;text-decoration:none;color:var(--accent,#8ea0ff);white-space:nowrap}`;document.head.appendChild(s)}
async function init(){if(!uid||!nickname)return;injectStyles();upgradeMediaRendering();panel();const btn=$('mediaBtn');if(btn)btn.onclick=()=>{document.querySelector('#app')?.classList.add('mobile-chat');$('chatView').style.display='none';$('mediaView').style.display='block';panel()};}
init().catch(console.error);
