import{getApps,getApp}from'https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js';
import{getFirestore,collection,getDocs,doc,query,orderBy,onSnapshot,updateDoc}from'https://www.gstatic.com/firebasejs/10.7.0/firebase-firestore.js';
const app=getApps().length?getApp():null;if(!app)throw new Error('Firebase app not ready');
const auth=getAuth(app),db=getFirestore(app);let uid='',users=[],path=null,unsub=null,lastTitle='';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function loadUsers(){if(users.length)return;const s=await getDocs(collection(db,'users'));users=s.docs.map(d=>d.data()).filter(x=>x.uid&&x.nickname)}
function chatPath(){const t=($('title')?.textContent||'').trim();if(!t||t==='Everyone')return'global';const u=users.find(x=>String(x.nickname).toLowerCase()===t.toLowerCase());return u?[uid,u.uid].sort().join('_'):null}
function style(){if($('mentionStyle'))return;const s=document.createElement('style');s.id='mentionStyle';s.textContent='.mentionBox{position:absolute;left:0;right:0;bottom:calc(100% + 6px);display:none;max-height:210px;overflow:auto;background:var(--panel,#151b27);border:1px solid #fff2;border-radius:13px;box-shadow:0 12px 35px #0008;z-index:80;padding:5px}.mentionBox.show{display:block}.mentionItem{width:100%;display:flex;align-items:center;gap:9px;padding:9px 10px;border:0;background:transparent;color:#e7ebf5;text-align:left;border-radius:9px;cursor:pointer}.mentionItem:hover,.mentionItem.active{background:#ffffff12}.mentionAvatar{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:var(--accent,#5865f2);font-size:12px}.mentionTag{color:var(--accent,#7c8cff);font-weight:600;background:#5865f214;border-radius:5px;padding:1px 3px}';document.head.appendChild(s)}
function box(){const c=$('composer');if(!c||$('mentionBox'))return; c.style.position='relative';const b=document.createElement('div');b.id='mentionBox';b.className='mentionBox';c.appendChild(b)}
function inputSetup(){const input=$('message'),b=$('mentionBox');if(!input||!b)return;if(input.dataset.mentionReady)return;input.dataset.mentionReady='1';let active=0;const render=()=>{const v=input.value, m=v.match(/(?:^|\s)@([\w.-]*)$/);if(!m){b.classList.remove('show');return}const term=m[1].toLowerCase();const matches=users.filter(u=>String(u.nickname).toLowerCase().startsWith(term)).slice(0,8);if(!matches.length){b.classList.remove('show');return}active=Math.min(active,matches.length-1);b.innerHTML=matches.map((u,i)=>`<button class="mentionItem ${i===active?'active':''}" data-n="${esc(u.nickname)}"><span class="mentionAvatar">${esc(String(u.nickname)[0].toUpperCase())}</span><span>@${esc(u.nickname)}</span></button>`).join('');b.classList.add('show')};const choose=n=>{const v=input.value,m=v.match(/(?:^|\s)@([\w.-]*)$/);if(!m)return;const start=m.index+(m[0].startsWith(' ')?1:0);input.value=v.slice(0,start)+'@'+n+' '+v.slice(start+m[0].trimStart().length);input.focus();input.dispatchEvent(new Event('input',{bubbles:true}));};input.addEventListener('input',render);input.addEventListener('keydown',e=>{if(!b.classList.contains('show'))return;const rows=[...b.querySelectorAll('.mentionItem')];if(e.key==='ArrowDown'){e.preventDefault();active=(active+1)%rows.length;rows.forEach((x,i)=>x.classList.toggle('active',i===active))}else if(e.key==='ArrowUp'){e.preventDefault();active=(active-1+rows.length)%rows.length;rows.forEach((x,i)=>x.classList.toggle('active',i===active))}else if(e.key==='Enter'&&rows[active]){e.preventDefault();choose(rows[active].dataset.n)}else if(e.key==='Escape')b.classList.remove('show')});b.addEventListener('mousedown',e=>{const x=e.target.closest('.mentionItem');if(x){e.preventDefault();choose(x.dataset.n)}});document.addEventListener('click',e=>{if(!b.contains(e.target)&&e.target!==input)b.classList.remove('show')})}
function decorate(){document.querySelectorAll('#messages .bubble').forEach(b=>{if(b.dataset.mentionDecorated)return;const raw=b.textContent||'';if(!raw.includes('@'))return;const safe=esc(raw).replace(/(^|\s)@([\w.-]+)/g,'$1<span class="mentionTag">@$2</span>');if(safe!==esc(raw)){b.innerHTML=safe;b.dataset.mentionDecorated='1'}})}
async function attachMentions(){if(!path||!unsub)return;const q=query(collection(db,'chats',path,'messages'),orderBy('createdAt','asc'));unsub();unsub=onSnapshot(q,s=>{s.forEach(x=>{const m=x.data();if(!m.text||m.sender!==uid||m.mentions)return;const found=[];const low=m.text.toLowerCase();users.forEach(u=>{if(new RegExp('(^|\\s)@'+String(u.nickname).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?=\\s|$)','i').test(m.text))found.push(u.uid)});const unique=[...new Set(found)];if(JSON.stringify(unique)!==JSON.stringify(m.mentions))updateDoc(doc(db,'chats',path,'messages',x.id),{mentions:unique}).catch(()=>{})});setTimeout(decorate,80)},()=>{} )}
async function run(){await loadUsers();style();box();inputSetup();const np=chatPath();if(np!==path){if(unsub)unsub();path=np;if(path){const q=query(collection(db,'chats',path,'messages'),orderBy('createdAt','asc'));unsub=onSnapshot(q,s=>{s.forEach(x=>{const m=x.data();if(m.text&&m.sender===uid&&!m.mentions){const found=users.filter(u=>new RegExp('(^|\\s)@'+String(u.nickname).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?=\\s|$)','i').test(m.text)).map(u=>u.uid);if(found.length)updateDoc(doc(db,'chats',path,'messages',x.id),{mentions:[...new Set(found)]}).catch(()=>{})}});setTimeout(decorate,100)},()=>{})}}}
function watch(){const t=$('title');if(!t)return;if(lastTitle!==t.textContent){lastTitle=t.textContent;run()}new MutationObserver(()=>{lastTitle='';run()}).observe(t,{childList:true,characterData:true,subtree:true});new MutationObserver(()=>decorate()).observe($('messages'),{childList:true,subtree:true})}
onAuthStateChanged(auth,u=>{if(u){uid=u.uid;setTimeout(watch,900)}});
