import{initializeApp}from'https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js';
import{getAuth,signInAnonymously,onAuthStateChanged,signOut}from'https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js';
import{getFirestore,collection,doc,setDoc,addDoc,query,orderBy,onSnapshot,serverTimestamp,getDocs,getDoc,updateDoc,deleteDoc,where}from'https://www.gstatic.com/firebasejs/10.7.0/firebase-firestore.js';
const config={apiKey:'AIzaSyBTDfFNbtXgf6I2OfwS_f6nCXLym2eSzc8',authDomain:'note-competition.firebaseapp.com',projectId:'note-competition',storageBucket:'note-competition.firebasestorage.app',messagingSenderId:'742140044633',appId:'1:742140044633:web:36cb08ff2aafc23c111848'};
const app=initializeApp(config),auth=getAuth(app),db=getFirestore(app);let uid=localStorage.getItem('uid'),nickname=localStorage.getItem('nickname');if(!uid||!nickname)location.href='index.html';
const $=id=>document.getElementById(id),appEl=$('app'),messages=$('messages'),input=$('message');let mode='group',selected=null,users=[],chatDocs={},globalDoc=null,unsubMsg=null,unsubMe=null,unsubChats=null,unsubGlobal=null,rowMenuId=null;
let prefs={};try{prefs=JSON.parse(localStorage.getItem('note-chat-prefs-'+uid)||'{}')||{}}catch{prefs={}};
const themes={midnight:{bubble:'#202633',text:'#f4f6fb',mine:'#5865f2',accent:'#5865f2',bg:'#080b12',panel:'#11151e'},ocean:{bubble:'#123b56',text:'#e8f7ff',mine:'#087ea4',accent:'#0b8dbd',bg:'#071522',panel:'#0e2940'},forest:{bubble:'#173d32',text:'#e7fff5',mine:'#247a5d',accent:'#2f9e78',bg:'#091914',panel:'#102a23'},sunset:{bubble:'#4b2b25',text:'#fff0e8',mine:'#c65f35',accent:'#d66b3d',bg:'#1b100d',panel:'#2b1915'},rose:{bubble:'#4b2638',text:'#ffeaf2',mine:'#b43d70',accent:'#c34d7b',bg:'#1a0c13',panel:'#2b1520'},lavender:{bubble:'#38305b',text:'#f1edff',mine:'#7661d9',accent:'#806ee8',bg:'#100d1e',panel:'#211b38'}};
function applyTheme(t){document.documentElement.style.setProperty('--bubble',t.bubble);document.documentElement.style.setProperty('--text',t.text);document.documentElement.style.setProperty('--mine',t.mine);document.documentElement.style.setProperty('--accent',t.accent);document.documentElement.style.setProperty('--bg',t.bg);document.documentElement.style.setProperty('--panel',t.panel);document.documentElement.style.setProperty('--panel2',t.bubble);$('bubbleColor').value=t.bubble;$('textColor').value=t.text;$('mineColor').value=t.mine;$('accentColor').value=t.accent;localStorage.setItem('note-theme-'+uid,JSON.stringify(t))}
applyTheme(JSON.parse(localStorage.getItem('note-theme-'+uid)||'null')||themes.midnight);
function avatar(n){return(n||'?').trim()[0]?.toUpperCase()||'?'}function esc(s){return String(s??'').replace(/[&<>'\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function linkify(s){return esc(s).replace(/(https?:\/\/[^\s<]+|www\.[^\s<]+)/gi,u=>{const trailing=(u.match(/[),.!?;:]+$/)||[''])[0],clean=u.slice(0,u.length-trailing.length),href=clean.toLowerCase().startsWith('www.')?'https://'+clean:clean;return `<a class="messageLink" href="${href}" target="_blank" rel="noopener noreferrer">${clean}</a>${trailing}`})}function chatId(a,b){return[a,b].sort().join('_')}function pget(k){return prefs[k]||{}}function savePrefs(){localStorage.setItem('note-chat-prefs-'+uid,JSON.stringify(prefs))}
function seconds(ts){return ts?.seconds||0}function timeShort(ts){if(!ts)return'';const d=ts.toDate?ts.toDate():new Date(ts);return d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}function dateTime(ts){return ts?timeShort(ts):''}
function isUnread(c){const r=Number(localStorage.getItem('note-read-'+uid+'-'+c.id)||0);return seconds(c.updatedAt)*1000>r&&c.lastSender!==uid}function markRead(id){localStorage.setItem('note-read-'+uid+'-'+id,String(Date.now()))}
function renderOnline(){const active=users.filter(u=>u.uid!==uid&&!u.kicked).slice(0,12);$('online').innerHTML='';active.forEach(u=>{const el=document.createElement('div');el.className='onlineItem';el.innerHTML=`<div class="onlineAvatar">${esc(avatar(u.nickname))}<span class="onlineDot"></span></div><div class="onlineName">${esc(u.nickname)}</div>`;el.onclick=()=>openPersonal(u);$('online').appendChild(el)});if(!active.length)$('online').innerHTML='<div style="color:#777f8e;font-size:12px;padding:12px 0">No other users yet</div>'}
function buildChats(filter=''){const list=[];const g={id:'global',name:'Everyone',other:null,lastMessage:globalDoc?.lastMessage||'Everyone signed in',lastSender:globalDoc?.lastSender||'',updatedAt:globalDoc?.updatedAt||null,pinned:!!pget('global').pinned};if(!filter||'everyone'.includes(filter.toLowerCase()))list.push(g);Object.values(chatDocs).forEach(d=>{const other=(d.members||[]).find(x=>x!==uid),u=users.find(x=>x.uid===other);if(!u||u.kicked)return;if(filter&&!u.nickname.toLowerCase().includes(filter.toLowerCase()))return;const p=pget(other);list.push({id:d.id,name:u.nickname,other,lastMessage:d.lastMessage||'Private message',lastSender:d.lastSender||'',updatedAt:d.updatedAt,pinned:!!p.pinned,muted:!!p.muted,archived:!!p.archived,blocked:!!p.blocked})});users.filter(u=>u.uid!==uid&&!u.kicked&&!chatDocs[chatId(uid,u.uid)]).forEach(u=>{if(filter&&!u.nickname.toLowerCase().includes(filter.toLowerCase()))return;const p=pget(u.uid);list.push({id:chatId(uid,u.uid),name:u.nickname,other:u.uid,lastMessage:'Tap to message',lastSender:'',updatedAt:null,pinned:!!p.pinned,muted:!!p.muted,archived:!!p.archived,blocked:!!p.blocked})});list.sort((a,b)=>(a.id==='global'?-1:b.id==='global'?1:0)||(b.pinned?-1:a.pinned?1:0)||(seconds(b.updatedAt)-seconds(a.updatedAt))||a.name.localeCompare(b.name));$('chatList').innerHTML='<div class="section">Chats</div>';list.forEach(c=>{const unread=isUnread(c),p=pget(c.id==='global'?'global':c.other),r=document.createElement('div');r.className='chatRow'+((mode==='group'&&c.id==='global')||(mode==='personal'&&selected?.uid===c.other)?' active':'');r.innerHTML=`<div class="chatAvatar ${c.id==='global'?'groupAvatar':''}">${c.id==='global'?'👥':esc(avatar(c.name))}</div><div class="chatInfo"><div class="chatName">${esc(c.name)} ${p.pinned?'📌':''}${p.muted?' 🔕':''}${p.archived?' 🗄️':''}${p.blocked?' 🚫':''}</div><div class="preview ${unread?'unread':''}">${esc(p.blocked?'Blocked':(c.lastSender===uid?'You: ':'')+c.lastMessage)}${unread?'<span class="unreadDot"></span>':''}</div></div><div class="time">${dateTime(c.updatedAt)}</div><button class="rowMenu" aria-label="Chat options">⋮</button>`;r.onclick=e=>{if(e.target.closest('.rowMenu')){e.stopPropagation();openRowMenu(c.id==='global'?'global':c.other);return}c.id==='global'?openGroup():openPersonal(users.find(u=>u.uid===c.other))};$('chatList').appendChild(r)})}
async function loadUsers(){try{const s=await getDocs(collection(db,'users'));users=s.docs.map(d=>d.data());renderOnline();buildChats($('search').value)}catch(e){console.error(e)}}
function subscribeChats(){if(unsubChats)unsubChats();const q=query(collection(db,'chats'),where('members','array-contains',uid));unsubChats=onSnapshot(q,s=>{chatDocs={};s.forEach(d=>chatDocs[d.id]={id:d.id,...d.data()});buildChats($('search').value)},e=>console.error('chat list',e));if(unsubGlobal)unsubGlobal();unsubGlobal=onSnapshot(doc(db,'chats','global'),s=>{globalDoc=s.exists()?s.data():null;buildChats($('search').value)},e=>console.error('global',e))}
function openRowMenu(id){rowMenuId=id;const p=pget(id);$('rowMenu').innerHTML=`<button data-a="pin">${p.pinned?'📌 Unpin':'📌 Pin to top'}</button><button data-a="mute">${p.muted?'🔔 Unmute':'🔕 Mute notifications'}</button><button data-a="archive">${p.archived?'📂 Unarchive':'🗄️ Archive'}</button>${id!=='global'?`<button data-a="block" class="danger">🚫 ${p.blocked?'Unblock':'Block user'}</button>`:''}<button data-a="delete" class="danger">🗑️ Remove chat from this device</button>`;$('rowMenuBack').classList.add('open')}
$('rowMenu').onclick=e=>{const b=e.target.closest('button');if(!b)return;const p=pget(rowMenuId),a=b.dataset.a;if(a==='pin')p.pinned=!p.pinned;if(a==='mute')p.muted=!p.muted;if(a==='archive')p.archived=!p.archived;if(a==='block')p.blocked=!p.blocked;if(a==='delete')delete prefs[rowMenuId];savePrefs();$('rowMenuBack').classList.remove('open');buildChats($('search').value)};$('rowMenuBack').onclick=e=>{if(e.target===$('rowMenuBack'))$('rowMenuBack').classList.remove('open')};
function stopMessages(){if(unsubMsg){unsubMsg();unsubMsg=null}}
function canEdit(m){if(!m.createdAt)return false;const d=m.createdAt.toDate?m.createdAt.toDate():new Date(m.createdAt);return Date.now()-d.getTime()<600000}
let messagePressTimer=null,messageMenu=null;
function closeMessageMenu(){if(messageMenu){messageMenu.remove();messageMenu=null}document.removeEventListener('pointerdown',closeMessageMenu,true)}
function showMessageMenu(w,id,m,x,y){closeMessageMenu();messageMenu=document.createElement('div');messageMenu.className='messageMenu';messageMenu.style.left=Math.min(Math.max(8,x),window.innerWidth-190)+'px';messageMenu.style.top=Math.min(Math.max(8,y),window.innerHeight-190)+'px';const editable=m.sender===uid&&canEdit(m);messageMenu.innerHTML=`${editable?'<button data-a="edit">✏️ Edit</button><button data-a="unsend" class="danger">↩ Unsend</button>':''}<button data-a="forward">↗ Forward</button>`;document.body.appendChild(messageMenu);messageMenu.onclick=e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.a;closeMessageMenu();if(a==='edit')editMessage(w,id,m);if(a==='unsend')unsend(id);if(a==='forward')forwardMessage(m)};setTimeout(()=>document.addEventListener('pointerdown',closeMessageMenu,true),0)}
async function forwardMessage(m){const choices=['Everyone',...users.filter(u=>u.uid!==uid&&!u.kicked).map(u=>u.nickname)];const target=prompt('Forward to:\n'+choices.join(', '));if(!target)return;const t=target.trim().toLowerCase();if(t==='everyone'){try{await setDoc(doc(db,'chats','global'),{type:'group',name:'Everyone',lastMessage:m.text||'',lastSender:uid,updatedAt:serverTimestamp()},{merge:true});await addDoc(collection(db,'chats','global','messages'),{text:m.text||'',sender:uid,senderName:nickname,createdAt:serverTimestamp(),edited:false,forwarded:true,forwardedFrom:m.senderName||'Unknown'});return}catch(e){return alert('Forward failed. Check Firestore Rules.')}}const u=users.find(v=>v.uid!==uid&&!v.kicked&&v.nickname.trim().toLowerCase()===t);if(!u)return alert('User not found. Type the exact nickname.');const path=chatId(uid,u.uid);try{await setDoc(doc(db,'chats',path),{type:'personal',members:[uid,u.uid],lastMessage:m.text||'',lastSender:uid,updatedAt:serverTimestamp()},{merge:true});await addDoc(collection(db,'chats',path,'messages'),{text:m.text||'',sender:uid,senderName:nickname,createdAt:serverTimestamp(),edited:false,forwarded:true,forwardedFrom:m.senderName||'Unknown'})}catch(e){alert('Forward failed. Check Firestore Rules.')}}
function renderMessage(x){const m=x.data(),w=document.createElement('div');w.className='bubbleWrap'+(m.sender===uid?' mine':'');w.innerHTML=`<div class="bubbleName ${m.sender===uid?'mineName':''}">${esc(m.senderName||'Unknown')}</div>${m.forwarded?`<div class="forwardedLabel">↗ Forwarded from ${esc(m.forwardedFrom||'Unknown')}</div>`:''}<div class="bubble">${linkify(m.text||'')}</div><div class="meta">${dateTime(m.createdAt)}${m.edited?' · edited':''}</div>`;let sx=0,sy=0;const start=e=>{if(e.pointerType==='mouse'&&e.button!==0)return;sx=e.clientX;sy=e.clientY;clearTimeout(messagePressTimer);messagePressTimer=setTimeout(()=>showMessageMenu(w,x.id,m,sx,sy),520)};const cancel=()=>clearTimeout(messagePressTimer);w.addEventListener('pointerdown',start);w.addEventListener('pointerup',cancel);w.addEventListener('pointercancel',cancel);w.addEventListener('pointerleave',e=>{if(e.pointerType==='mouse')cancel()});w.addEventListener('pointermove',e=>{if(Math.hypot(e.clientX-sx,e.clientY-sy)>12)cancel()});w.addEventListener('contextmenu',e=>{e.preventDefault();showMessageMenu(w,x.id,m,e.clientX,e.clientY)});return w}
function subscribeMessages(path){stopMessages();messages.innerHTML='<div class="empty">Loading messages…</div>';const q=query(collection(db,'chats',path,'messages'),orderBy('createdAt','asc'));unsubMsg=onSnapshot(q,s=>{messages.innerHTML='';if(s.empty){messages.innerHTML='<div class="empty">No messages yet. Say hello 👋</div>';return}s.forEach(x=>messages.appendChild(renderMessage(x)));messages.scrollTop=messages.scrollHeight},e=>{console.error(e);messages.innerHTML='<div class="empty">Could not load messages. Check Firestore Rules.</div>'})}
function editMessage(w,id,m){const b=w.querySelector('.bubble'),old=m.text||'';b.innerHTML=`<div class="editBox"><input maxlength="2000"><button class="save">Save</button><button class="cancel">Cancel</button></div>`;const inp=b.querySelector('input');inp.value=old;inp.focus();b.querySelector('.save').onclick=async()=>{if(!canEdit(m))return alert('The 10-minute edit window has expired.');const text=inp.value.trim();if(!text)return;try{await updateDoc(doc(db,'chats',mode==='group'?'global':chatId(uid,selected.uid),'messages',id),{text,edited:true,editedAt:serverTimestamp()})}catch(e){alert('Edit failed. Check Firestore Rules.')}};b.querySelector('.cancel').onclick=()=>b.textContent=old;inp.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();b.querySelector('.save').click()}if(e.key==='Escape')b.querySelector('.cancel').click()}}
async function unsend(id){if(!confirm('Unsend this message for everyone?'))return;const path=mode==='group'?'global':chatId(uid,selected.uid);try{await deleteDoc(doc(db,'chats',path,'messages',id))}catch(e){alert('Unsend failed. Check Firestore Rules.')}}
async function sendMsg(){if(mode==='personal'&&pget(selected.uid).blocked)return alert('This user is blocked. Unblock the chat to send messages.');const text=input.value.trim();if(!text||mode==='personal'&&!selected)return;const path=mode==='group'?'global':chatId(uid,selected.uid);input.value='';try{const data=mode==='group'?{type:'group',name:'Everyone',lastMessage:text,lastSender:uid,updatedAt:serverTimestamp()}:{type:'personal',members:[uid,selected.uid],lastMessage:text,lastSender:uid,updatedAt:serverTimestamp()};await setDoc(doc(db,'chats',path),data,{merge:true});await addDoc(collection(db,'chats',path,'messages'),{text,sender:uid,senderName:nickname,createdAt:serverTimestamp(),edited:false})}catch(e){console.error(e);alert('Message could not be sent. Check Firestore Rules.')}}
$('send').onclick=sendMsg;input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMsg()}};
function openGroup(){mode='group';selected=null;appEl.classList.add('mobile-chat');$('title').textContent='Everyone';$('subtitle').textContent='Group chat • Everyone signed in';$('topAvatar').textContent='👥';$('message').placeholder='Message everyone…';$('chatView').style.display='flex';$('mediaView').style.display='none';$('composer').classList.remove('blocked');markRead('global');subscribeMessages('global');buildChats($('search').value)}
function openPersonal(u){if(!u)return;mode='personal';selected=u;appEl.classList.add('mobile-chat');$('title').textContent=u.nickname;$('subtitle').textContent=pget(u.uid).blocked?'Blocked':'Private message';$('topAvatar').textContent=avatar(u.nickname);$('message').placeholder=`Message ${u.nickname}…`;$('chatView').style.display='flex';$('mediaView').style.display='none';$('composer').classList.toggle('blocked',!!pget(u.uid).blocked);markRead(chatId(uid,u.uid));subscribeMessages(chatId(uid,u.uid));buildChats($('search').value)}
$('back').onclick=()=>{appEl.classList.remove('mobile-chat');stopMessages();buildChats($('search').value)};$('search').oninput=()=>buildChats($('search').value);$('newChat').onclick=()=>{$('search').focus();$('search').select()};
$('mediaBtn').onclick=async()=>{appEl.classList.add('mobile-chat');$('chatView').style.display='none';$('mediaView').style.display='block';$('gallery').innerHTML='<div class="empty">Loading media…</div>';try{const r=await fetch('https://api.github.com/repos/Iammdtanvirrahman2007/note.com/contents/media?ref=main');const fs=await r.json();const imgs=Array.isArray(fs)?fs.filter(f=>f.type==='file'&&/\.(png|jpe?g|gif|webp|bmp|svg)$/i.test(f.name)):[];$('gallery').innerHTML='';imgs.forEach(f=>{const c=document.createElement('div');c.className='photo';c.innerHTML=`<img loading="lazy" src="https://raw.githubusercontent.com/Iammdtanvirrahman2007/note.com/main/media/${encodeURIComponent(f.name)}"><div>${esc(f.name)}</div>`;$('gallery').appendChild(c)});if(!imgs.length)$('gallery').innerHTML='<div class="empty">No images yet.</div>'}catch(e){$('gallery').innerHTML='<div class="empty">Could not load media.</div>'}};
$('themeBtn').onclick=()=>$('themeModal').classList.add('open');$('themeHome').onclick=()=>$('themeModal').classList.add('open');$('closeTheme').onclick=()=>$('themeModal').classList.remove('open');$('themeModal').onclick=e=>{if(e.target===$('themeModal'))$('themeModal').classList.remove('open')};document.querySelectorAll('.preset').forEach(b=>b.onclick=()=>applyTheme(themes[b.dataset.t]));['bubbleColor','textColor','mineColor','accentColor'].forEach(id=>$(id).oninput=()=>{const old=JSON.parse(localStorage.getItem('note-theme-'+uid)||'null')||themes.midnight;applyTheme({...old,bubble:$('bubbleColor').value,text:$('textColor').value,mine:$('mineColor').value,accent:$('accentColor').value})});
$('logout').onclick=async()=>{localStorage.clear();stopMessages();if(unsubChats)unsubChats();if(unsubGlobal)unsubGlobal();if(unsubMe)unsubMe();try{await signOut(auth)}catch{}location.href='index.html'};
onAuthStateChanged(auth,async u=>{if(!u){try{await signInAnonymously(auth)}catch(e){console.error(e);return}}else{try{uid=u.uid;localStorage.setItem('uid',uid);prefs={};try{prefs=JSON.parse(localStorage.getItem('note-chat-prefs-'+uid)||'{}')||{}}catch{prefs={}}applyTheme(JSON.parse(localStorage.getItem('note-theme-'+uid)||'null')||themes.midnight);const ref=doc(db,'users',uid),s=await getDoc(ref);if(s.exists()&&s.data().kicked){document.body.innerHTML='<div style="height:100dvh;display:grid;place-items:center;background:#080b12;color:#fff;text-align:center;font-family:Arial"><div><div style="font-size:60px">⛔</div><h2>You have been kicked</h2><p style="color:#9ca6bf">An administrator has blocked this account.</p><a href="index.html" style="color:#aebaff">Return to login</a></div></div>';return}await setDoc(ref,{nickname,nicknameLower:nickname.trim().toLowerCase(),uid,lastSeen:serverTimestamp()},{merge:true});unsubMe=onSnapshot(ref,snap=>{if(snap.exists()&&snap.data().kicked){alert('You have been kicked by an administrator.');localStorage.clear();location.href='index.html'}});await loadUsers();subscribeChats();if(innerWidth>760)openGroup();else{appEl.classList.remove('mobile-chat');buildChats($('search').value)}}catch(e){console.error(e);$('chatList').innerHTML='<div class="empty">Could not connect to Messenger. Check Firestore Rules.</div>'}}});