import{getApps,getApp}from'https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js';
import{getFirestore,collection,doc,getDocs,getDoc,query,orderBy,onSnapshot,updateDoc,serverTimestamp,setDoc}from'https://www.gstatic.com/firebasejs/10.7.0/firebase-firestore.js';

const app=getApps().length?getApp():null;if(!app)throw new Error('Firebase app not ready');
const auth=getAuth(app),db=getFirestore(app);let uid=localStorage.getItem('uid'),nickname=localStorage.getItem('nickname'),unsubMsgs=null,unsubTyping=null,typingTimer=null,lastPath=null;
const $=id=>document.getElementById(id);const chatId=(a,b)=>[a,b].sort().join('_');
function ensureTyping(){if($('typingIndicator'))return;const el=document.createElement('div');el.id='typingIndicator';el.className='typingIndicator';el.innerHTML='<span class="typingDots"><i></i><i></i><i></i></span><span class="typingText"></span>';const m=$('messages');m?.parentElement?.insertBefore(el,m);}
function style(){if(document.getElementById('readTypingStyle'))return;const s=document.createElement('style');s.id='readTypingStyle';s.textContent='.typingIndicator{display:none;align-items:center;gap:8px;min-height:24px;padding:2px 16px 6px;color:#9ca6bf;font-size:12px}.typingIndicator.show{display:flex}.typingDots{display:inline-flex;gap:3px;padding:7px 9px;border-radius:12px;background:var(--bubble,#202633)}.typingDots i{width:4px;height:4px;border-radius:50%;background:currentColor;animation:td 1.2s infinite}.typingDots i:nth-child(2){animation-delay:.15s}.typingDots i:nth-child(3){animation-delay:.3s}@keyframes td{0%,60%,100%{opacity:.25;transform:translateY(0)}30%{opacity:1;transform:translateY(-2px)}}.seenStatus{margin-left:5px;font-size:11px;opacity:.8}.seenAvatars{display:inline-flex;margin-left:5px}.seenAv{display:inline-grid;place-items:center;width:18px;height:18px;border-radius:50%;font-size:9px;background:var(--accent,#5865f2);color:#fff;margin-left:-3px;border:1px solid var(--bg,#080b12)}';document.head.appendChild(s)}
async function findPath(){const title=($('title')?.textContent||'').trim();if(title==='Everyone'||!title)return'global';const s=await getDocs(collection(db,'users'));const u=s.docs.map(d=>d.data()).find(x=>String(x.nickname||'').trim().toLowerCase()===title.toLowerCase());return u?chatId(uid,u.uid):null}
function setTyping(show,text=''){const el=$('typingIndicator');if(!el)return;el.classList.toggle('show',show);const t=el.querySelector('.typingText');if(t)t.textContent=text}
async function publishTyping(path,isTyping){try{await setDoc(doc(db,'chats',path,'typing',uid),{uid,nickname,isTyping,updatedAt:serverTimestamp()},{merge:true})}catch(e){console.debug('typing',e)}}
async function setupTyping(path){if(unsubTyping)unsubTyping();unsubTyping=onSnapshot(collection(db,'chats',path,'typing'),s=>{const now=Date.now();const active=s.docs.map(d=>d.data()).filter(x=>x.uid!==uid&&x.isTyping&&x.updatedAt&&(now-(x.updatedAt.toMillis?x.updatedAt.toMillis():0)<5000));setTyping(active.length>0,active.length===1?`${active[0].nickname||'Someone'} is typing…`:`${active.length} people are typing…`)},()=>setTyping(false));const input=$('message');if(!input)return;input.oninput=()=>{publishTyping(path,true);clearTimeout(typingTimer);typingTimer=setTimeout(()=>publishTyping(path,false),1800)};input.onblur=()=>{clearTimeout(typingTimer);publishTyping(path,false)}}
async function markVisible(path){if(unsubMsgs)unsubMsgs();const q=query(collection(db,'chats',path,'messages'),orderBy('createdAt','asc'));unsubMsgs=onSnapshot(q,async s=>{const writes=[];s.forEach(x=>{const m=x.data();if(m.sender!==uid&&!m.seenBy?.[uid])writes.push(updateDoc(doc(db,'chats',path,'messages',x.id),{[`seenBy.${uid}`]:serverTimestamp()}))});if(writes.length)await Promise.allSettled(writes);renderSeen(s.docs.map(x=>({id:x.id,data:x.data()})))},e=>console.debug('seen',e))}
function renderSeen(items){const wraps=[...document.querySelectorAll('#messages .bubbleWrap')];let j=0;for(const item of items){const m=item.data;if(m.sender!==uid)continue;const w=wraps[j++];if(!w)continue;let meta=w.querySelector('.meta');if(!meta)continue;meta.querySelector('.seenStatus')?.remove();const seen=Object.keys(m.seenBy||{}).filter(x=>x!==uid);if(!seen.length)continue;const names=[];seen.forEach(id=>{const u=window.__tanmiraUsers?.find(v=>v.uid===id);if(u)names.push(u.nickname)});const span=document.createElement('span');span.className='seenStatus';if(lastPath==='global'){span.textContent=names.length?` · Seen by ${names.join(', ')}`:` · Seen by ${seen.length}`}else span.textContent=' · Seen';meta.appendChild(span)}}
async function run(){style();ensureTyping();uid=auth.currentUser?.uid||localStorage.getItem('uid');nickname=localStorage.getItem('nickname');if(!uid)return;const path=await findPath();if(!path||path===lastPath)return;lastPath=path;await setupTyping(path);await markVisible(path);const observer=new MutationObserver(()=>setTimeout(()=>{if(lastPath)markVisible(lastPath)},80));observer.observe($('messages'),{childList:true,subtree:true})}
function watchChat(){const t=$('title');if(!t)return;new MutationObserver(()=>{lastPath=null;run()}).observe(t,{childList:true,characterData:true,subtree:true});run()}
onAuthStateChanged(auth,u=>{if(u){uid=u.uid;setTimeout(watchChat,500)}});
window.__tanmiraReadTyping={run};
